// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcncsqjulsndaqbckoce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjbmNzcWp1bHNuZGFxYmNrb2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTM5MDUsImV4cCI6MjA2NjU4OTkwNX0.NyoV9Kee6iNUBMVr8fDiLLOX4j99oKhPfw-0b6AjZpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);